### ISSUE TITLE
Problem on fuse.LoggingMixIn

### ISSUE THREAD

**Issue by ppatierno** [remakeelectric/mqtt-malaria#20]
Hello,
I have just git cloned mqtt malaria but when I lunch :

./malaria publish -h

just for help, I receive the following error :

Traceback (most recent call last):
  File "./malaria", line 30, in <module>
    import beem.main
  File "/home/ppatierno/mqtt/mqtt-malaria/beem/main.py", line 34, in <module>
    import beem.cmds
  File "/home/ppatierno/mqtt/mqtt-malaria/beem/cmds/**init**.py", line 2, in <module>
    import beem.cmds.subscribe
  File "/home/ppatierno/mqtt/mqtt-malaria/beem/cmds/subscribe.py", line 34, in <module>
    import beem.listen
  File "/home/ppatierno/mqtt/mqtt-malaria/beem/listen.py", line 166, in <module>
    class MalariaWatcherStatsFS(fuse.LoggingMixIn, fuse.Operations):
AttributeError: 'module' object has no attribute 'LoggingMixIn'

I have Ubuntu 12.04 and python-fuse seems to be updated to 0.2 version.

Paolo.

**Comment by Panchatcharam** [comment]
Hi Karlp,
I'm also running into the same issue as described by ppatierno, I did follow the steps as outlined by you. Presently I'm in my Python virtual environment and I run the  "pip install -e .", the following are observed on the screen.

(virtualenvironment) developer@app-dev-dt0:~/work/mosq_benchMark/mqtt-malaria-master$ pip install -e .
Obtaining file:///home/developer/work/mosq_benchMark/mqtt-malaria-master
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/developer/work/mosq_benchMark/mqtt-malaria-master/setup.py", line 13, in <module>
        version=version.get_git_version(),
      File "version.py", line 90, in get_git_version
        raise ValueError("Cannot find the version number!")
    ValueError: Cannot find the version number!
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/developer/work/mosq_benchMark/mqtt-malaria-master/

Could you throw some lights on it, I would like to use malaria to validate mosquitto.

**Comment by karlp** [comment]
That's not the same problem at atll. the error messages are completely different.  You look like you have a tarball of the source instead of a a git clone of the code.  Hence, the "get_get_version" is failing.

**Comment by Panchatcharam** [comment]
Thanks, Karlp.  I did git clone and was able to run the tests successfully.  
I did run publisher and subscriber with below options,
```
./malaria publish -t -n 10000 -P 200 -T 0.5
./malaria subscribe -n 10000 -N 200
```
and observed the response after running for a while
```
INFO:beem.listen:beem.listr-15784:Still waiting for 583817 messages
INFO:beem.listen:beem.listr-15784:Still waiting for 583719 messages
INFO:beem.listen:beem.listr-15784:Still waiting for 583619 messages
INFO:beem.listen:beem.listr-15784:Still waiting for 583522 messages
INFO:beem.listen:beem.listr-15784:Still waiting for 583514 messages
INFO:beem.listen:beem.listr-15784:Still waiting for 583294 messages
INFO:beem.listen:beem.listr-15784:Still waiting for 583193 messages
INFO:beem.listen:beem.listr-15784:Still waiting for 583099 messages
WARNING:beem.listen:beem.listr-15784:Drop count has increased by 666
INFO:beem.listen:beem.listr-15784:Still waiting for 582994 messages
ERROR:beem.listen:beem.listr-15784:Detected drops are occuring, aborting test!
Clientid: beem.listr-15784
Total clients tracked: 200
Total messages: 1417006
Total time: 14199.68 secs
Messages per second: 99 (10.020902 ms per message)
Test aborted, unable to gather duplicate/missing stats
Flight time mean:   503.00 ms
Flight time stddev: 298.17 ms
Flight time min:    0.32 ms
Flight time max:    8659.92 ms
```
what's drop here and I see the subscriber is aborted after a certain count. how this is determined, please shed some lights.

**Comment by karlp** [comment]
This is a close issue.  If you're still having issues please please please make your own issue.
