### ISSUE TITLE
mosquitto-auth-plug

### ISSUE THREAD

**Issue by dongmkim** [remakeelectric/mqtt-malaria#23]
hi.

my mosquitto server use mosquitto-auth-plug

https://github.com/jpmens/mosquitto-auth-plug

I would like to know whether you can test the server on which you installed the plugin from malaria 

im sorry. I can not speak English.

**Comment by karlp** [comment]
the target broker you configure and run yourself.  malaria only sets up client loads.  It can set up the client loads to be brokers themselves bridging to the target, but I can't imagine you'd want each of _them_ to use the auth plugin.

**Comment by dongmkim** [comment]
thank you!!!
