### ISSUE TITLE
The Mosquitto Python module has been donated to the Eclipse Paho project.

### ISSUE THREAD

**Issue by aishi1979** [remakeelectric/mqtt-malaria#27]
Since The Mosquitto Python module has been donated to the Eclipse Paho project. According to the masquitto's suggestion, the following migration is better to be considered.
Only few lines in listen.py and load.py need to be updated. Please check: http://mosquitto.org/documentation/python/

"Existing users of the Mosquitto Python module should find it very easy to port their code to the Paho version.
import mosquitto
client = mosquitto.Mosquitto()
becomes
import paho.mqtt.client as paho
client = paho.Client()
"

**Comment by karlp** [comment]
Yep, this had been updated locally and not committed, thanks for reminding me on this.
