### ISSUE TITLE
How do I publish message with username and password ?

### ISSUE THREAD

**Issue by Jameswz** [remakeelectric/mqtt-malaria#30]
does malaria support username and password config ? How to do this ?

Thank you so much

**Comment by karlp** [comment]
Not presently, it wasn't an interesting use case when we built this.  You could add it without too much problem, just need to set the username/password before you call connect, in eg: https://github.com/remakeelectric/mqtt-malaria/blob/master/beem/load.py#L71 for non-bridging

For bridging, it's a little more complicated, you probably want to add things to the config file generator at https://github.com/remakeelectric/mqtt-malaria/blob/master/beem/bridge.py#L194
