### ISSUE TITLE
Fixed Message Size

### ISSUE THREAD

**Issue by matriawan** [remakeelectric/mqtt-malaria#32]
How to set fixed message size ? -s parameter or without gaussian ?

**Comment by karlp** [comment]
There's probably nothing built in for it, it wasn't something I was particularly trying to test.  It should be relatively straightforward to add a new message generator though.

**Comment by matriawan** [comment]
thanks before, i've been trying to make it,

**Comment by matriawan** [comment]
i've problem, if -s 100 work fine, but if -s < 10 that's got problem. in file "beem/msgs.py"

def GaussianSize(cid, sequence_size, target_size):
    """
    Message generator creating gaussian distributed message sizes
    centered around target_size with a deviance of target_size / 20
    """
    num = 1
    while num <= sequence_size:
        topic = "mqtt-malaria/%s/data/%d/%d" % (cid, num, sequence_size)
        #real_size = int(random.gauss(target_size, target_size / 20))
        real_size = int((target_size - 18)) if target_size > 10 else (int(target_size))
        payload = ''.join(random.choice(string.hexdigits) for _ in range(real_size))
        yield (num, topic, payload)
        num = num + 1
