### ISSUE TITLE
Incompatibility with RabbitMQ

### ISSUE THREAD

**Issue by subrsi9** [remakeelectric/mqtt-malaria#34]
There is a problem while subscribing to RabbitMQ:

The topic name with RabbitMQ is (In my computer) "mqtt-malaria/beem/loadr-TMA0004ALKVTAXL-84458-0/data/98/100"

The topic name with Mosquito is (In my computer) " mqtt-malaria/beem.loadr-TMA0004ALKVTAXL-84994-0/data/100/100"

In "trackers.py" the topic name splits with "/" and self.mid = int(segments[3])=> this is working fine for Mosquito subscription.

But this is an issue with RabbitMQ,  since RabbitMQ topic name appended with "/" ( beem/loadr ) instead of  "." (beem.loadr) it throws the run time exception.

In my local, I changed the "trackers.py" self.mid = int(segments[4]) for my rabbitMQ scalable test, its working in my local.  

The MQTT-Malaria simulator should be generic for all MQTT protocol implementation message brokers not only for Mosquito MQTT broker.

**Comment by karlp** [comment]
I'm afraid I don't really understand.  "." characters are allowed in topics, and are not considered any sort of separator by the MQTT spec.  If Rabbit is interpreting them specially, as you seem to be saying, hence your changee, then _Rabbit_ is not compliant with MQTT, not the otherway around.
