### ISSUE TITLE
How do you specify a topic with Publish

### ISSUE THREAD

**Issue by haroonniazi** [remakeelectric/mqtt-malaria#38]
The current publish command sends the messages to **amqp.topic** exchange. Is there a way where we can specify to send the messages to a specific topic(s)?

**Comment by karlp** [comment]
You'll have to edit the source for that.  For testing like this, the actual name of topics isn't interesting, only that the subscribers match the publishers so you can collect stats properly.

**Comment by janainascal** [comment]
Please consider reopen this issue.
I'm using Kafka and I would like to test using this awesome project.
When I test a huge number of messages, it start to create to many topics, and kafka slows down.

For now, I will look the source code, but would be nice to have this as an option.

**Comment by karlp** [comment]
@janainascal re-opening it won't change anything.  you have to edit the source to make that change, and I'm not going to be doing that work.  However, if kafka slows down because there's too many topics, I'd suggest you consider filing a ticket with kafka....
